<a href="https://colab.research.google.com/github/1994shuklaanand/Tobacco-DataAnalysis-And-Dashboard-Creation/blob/main/Tobacco_DataAnalysis_And_Dashboard_Creation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
table=pd.read_html('https://www.findeasy.in/tobacco-use-among-adults-in-india/')

In [4]:
len(table)

3

In [5]:
table[0]

,0,1,2,3
0,#,States & Union Territories,Women (15 years & above),Men (15 years & above)
1,1,Andaman & Nicobar,31.3 %,58.7 %
2,2,AP,3.8%,22.6%
3,3,Arunachal,18.8%,50.3%
4,4,Assam,22.1%,51.8%
5,5,Bihar,5.0%,48.8%
6,6,Chandigarh,0.6%,12.1%
7,7,Chattishgarh,17.3%,43.1%
8,8,D&N,2.9%,38.6%
9,9,Delhi,2.2%,26.3%
10,10,Goa,2.6%,18.2%
11,11,Gujarat,8.7%,41.1%
12,12,Haryana,2.5%,29.1%
13,13,Himachal Pradesh,1.7%,32.3%
14,14,J&K,3.6%,38.3%
15,15,Jharkhand,8.4%,47.4%
16,16,Karnataka,8.5%,27.1%
17,17,Kerala,2.2%,16.9%
18,18,Ladakh,3.2%,35.7%
19,19,Lakshadweep,17.5%,28.5%
20,20,Maharashtra,10.9%,33.8%
21,21,Manipur,43.1%,58.1%
22,22,Meghalaya,28.2%,57.7%
23,23,Mizoram,61.6%,72.9%
24,24,Madhya Pradesh,10.2%,46.5%
25,25,Nagaland,13.7%,48.4%
26,26,Odisha,26.0%,51.6%
27,27,Puducherry,2.6%,14.8%
28,28,Punjab,0.4%,12.9%
29,29,Rajasthan,6.9%,42.0%
30,30,Sikkim,11.7%,41.3%
31,31,Tamil Nadu,4.9%,20.1%
32,32,Telangana,5.6%,22.3%
33,33,Tripura,50.4%,56.9%
34,34,Uttar Pradesh,8.4%,44.1%
35,35,Uttarakhand,4.6%,33.7%
36,36,West Bengal,10.8%,48.1%
37,NaN,India,8.9%,38.0%

In [12]:
csv_file_path = pd.read_csv('/content/tobaco1.csv')

In [16]:
final_tobaco = pd.read_excel('/content/TOBACO FINAL.xlsx')

In [17]:
final_tobaco.head()

,States & UnionÂ Territories,Women (15 years & above),Men (15 years & above)
0,Andaman & Nicobar,0.313,0.587
1,AP,0.038,0.226
2,Arunachal,0.188,0.503
3,Assam,0.221,0.518
4,Bihar,0.050,0.488

In [13]:
csv_file_path.head()

  States & Union Territories Women (15 years & above) Men (15 years & above)
0          Andaman & Nicobar                   31.30%                 58.70%
1                         AP                    3.80%                 22.60%
2                  Arunachal                   18.80%                 50.30%
3                      Assam                   22.10%                 51.80%
4                      Bihar                    5.00%                 48.80%

In [19]:
table[0].to_csv('/content/tobaco1.csv' , index=False)